# Nginx RTMP 配置文件
# 使用方法: nginx -c /path/to/this/file

worker_processes 1;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;
        
        application live {
            live on;
            record off;
            
            # 允许所有客户端连接
            allow publish all;
            allow play all;
        }
    }
}

http {
    server {
        listen 8080;
        location / {
            root /tmp;
        }
    }
}

